# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import author_pb2 as author__pb2
import genre_pb2 as genre__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x1a\x0c\x61uthor.proto\x1a\x0bgenre.proto\"i\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x17\n\x06\x61uthor\x18\x03 \x01(\x0b\x32\x07.Author\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x14\n\x0cpublish_year\x18\x05 \x01(\x05\x42\x0b\x42\tBookProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\tBookProto'
  _BOOK._serialized_start=41
  _BOOK._serialized_end=146
# @@protoc_insertion_point(module_scope)
